### ISSUE TITLE
error

### ISSUE THREAD

**Issue by danny95928** [Digital-Twin-Operational-Platform/Cristallo#10]
flask.cli.NoAppException: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory

I have tried both in powershell and pycharm and still can not find the right run environment, where went wrong?
![image](https://github.com/Digital-Twin-Operational-Platform/Cristallo/assets/38828580/b3963118-8d20-4111-9af9-4baf38a43093)

**Comment by msbonney** [comment]
Hi there,

It is pretty difficult to debug this issue since no-one on the team uses pycharm. But I am also seeing it on powershell. The majority of the development team using unix-based systems (Linux/Mac) so we did not verify the powershell deployment.

I have been able to recreate the error in powershell. I will look into a solution

**Comment by msbonney** [comment]
While I haven't solved the issue in pycharm, I believe I have a solution to Powershell.

You simply need to replace       run.py       with      ".\run.py"    such that the powershell commands are:

# PowerShell (Windows)
(venv) C:\cristallo> $env:FLASK_APP=".\run.py"
(venv) C:\cristallo> $env:FLASK_DEBUG=1
(venv) C:\cristallo> flask run

Can you please try this and let me know if that works? I will then update the readme file.

-Matt

**Comment by danny95928** [comment]
thks for the help, but i still cannot get the last step, i try both PowerShell (Windows) and cmd, the run.py and FLASK_DEBUG all settled. 
the cmd error is:
![image](https://github.com/Digital-Twin-Operational-Platform/Cristallo/assets/38828580/e5962d73-19f3-4139-b0d9-71ebba98a952)
and the Powershell error shows:
![image](https://github.com/Digital-Twin-Operational-Platform/Cristallo/assets/38828580/510eedeb-986e-4550-8023-2028cbbaf188)
flask : The item 'flask' is not recognized as the name of a cmdlet, function, script file, or executable. Please check the spelling of the name,
If a path is included, make sure the path is correct and try again.
Location Line: 1 Character: 1
+ flask run
+ ~~~~~
     + CategoryInfo : ObjectNotFound: (flask:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by msbonney** [comment]
For the powershell, your commands for run.py are incorrect. Here is the correct inputs 

![Screenshot 2023-08-08 124302](https://github.com/Digital-Twin-Operational-Platform/Cristallo/assets/71449379/69a12a06-fbbe-42b3-87b7-b3c45d0d538d)


For the CMD, I am unsure of the issue. It seems to be an interdependence within Flask. After some searching, Jinja stopped supporting escape. So Flask will need to be upgraded to 2.x. I will update the requirements.txt to reflect this. As a test can you pip install this way:

#install
pip install Flask Scipy Plotly Wtform


Try that on cmd and let me know.

**Comment by danny95928** [comment]
thks for your help it works!!!!!!!
this is what i do:

run powershell as administrator

reactivate the environment

pip install Flask Scipy Plotly Wtform

pip install Jinja2==3.0.3

**Comment by danny95928** [comment]
btw
it also works on cmd

**Comment by danny95928** [comment]
![image](https://github.com/Digital-Twin-Operational-Platform/Cristallo/assets/38828580/dd9cb0e6-afd6-4bbb-9db0-dcddb814e6ee)
😀
